name: Build & Deploy to GitHub Pages

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      # Install root deps (where package.json lives)
      - name: Install dependencies (root)
        run: npm ci || npm install

      # Build the client app from its folder using Vite directly
      - name: Build frontend (client/)
        working-directory: client
        run: npx vite build --debug

      # Show what got built for easy debugging
      - name: List build output
        run: |
          ls -la client || true
          ls -la client/dist || true

      # Hard fail if index.html isn't there
      - name: Verify built index.html
        run: |
          test -f client/dist/index.html || (echo "client/dist/index.html missing" && exit 1)

      # Add custom domain + SPA fallback
      - name: Add CNAME and SPA fallback
        run: |
          echo "info.thetradescout.us" > client/dist/CNAME
          cp client/dist/index.html client/dist/404.html || true

      # Upload the site artifact for Pages
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: client/dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
