name: Build & Deploy to GitHub Pages

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      # Install root deps (vite lives here)
      - name: Install dependencies (root)
        run: npm ci || npm install

      # If the client has its own package.json, install there too (harmless if absent)
      - name: Install dependencies (client if present)
        working-directory: client
        run: |
          if [ -f package.json ]; then
            npm ci || npm install
          else
            echo "No client/package.json; continuing"
          fi

      # Build using root config (vite.config.ts with root:'client'); if that fails, try inside client/
      - name: Build frontend
        shell: bash
        run: |
          set -e
          echo "Trying: npx vite build (root)"
          if npx vite build --debug; then
            echo "Built via root config."
          else
            echo "Root build failed. Trying inside client/…"
            cd client
            npx vite build --debug
            cd ..
          fi

      - name: Show build output
        run: |
          echo "== ls client =="
          ls -la client || true
          echo "== ls client/dist =="
          ls -la client/dist || true

      - name: Verify built index.html
        run: |
          test -f client/dist/index.html || (echo "ERROR: client/dist/index.html missing. Check the Build frontend step logs." && exit 1)

      - name: Add CNAME and SPA fallback
        run: |
          echo "info.thetradescout.us" > client/dist/CNAME
          cp client/dist/index.html client/dist/404.html || true

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: client/dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
